name: bean_go
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  collection: ^1.18.0
  auto_route: ^9.2.2
  riverpod_annotation: ^2.1.1
  intl_utils: ^2.8.3
  intl: ^0.19.0
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  equatable: ^2.0.7
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  firebase_analytics: ^11.3.5
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  firebase_messaging: ^15.1.5
  url_launcher: ^6.2.5
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.0
  auto_size_text: ^3.0.0
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.0.0
  internet_connection_checker_plus: ^2.3.0
  flutter_local_notifications: ^19.0.0
  hive: ^2.2.3
  isar_flutter_libs: ^4.0.0-dev.13
#  native_auth: ^1.0.6
  image_picker: ^1.0.7
  path: ^1.8.3
  webview_flutter: ^4.7.0
  rxdart: ^0.28.0
  infinite_scroll_pagination: ^4.0.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  device_preview: ^1.2.0
  awesome_snackbar_content: ^0.1.5
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.1
  flutter_animated_button: ^2.0.4
  animated_text_kit: ^4.2.3
  path_provider: ^2.1.5
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^9.1.5
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^9.0.0
  riverpod_generator: ^2.2.3
  json_serializable: ^6.7.1
  flutter_gen: ^5.3.1
  hive_generator: ^2.0.1
  melos: ^6.2.0
  flutter_gen_runner: ^5.10.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: pl # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: assets/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/gen # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false


flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

flutter_native_splash:
  color: "#ffffff" # Optional
  image: assets/images/splash.png # Required

  android_12:
    image: assets/images/splash.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/splash.png
    icon_background_color_dark: "#121212"

  # Optional
  integrations:
    flutter_svg: true